spring.application.name=production-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/faclovers_auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:faclovers}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:faclovers123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:faclovers_microservices_lab_secret_key_with_at_least_32_chars}
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
